CREATE TABLE index_list (
id INT AUTO_INCREMENT
,version INT NOT NULL DEFAULT 1
,created_at TIMESTAMP NOT NULL DEFAULT NOW()
,updated_at TIMESTAMP NOT NULL
,name VARCHAR(64) NOT NULL
,PRIMARY KEY(id)
,UNIQUE(name)
) ENGINE=InnoDB;