CREATE TABLE mapping_list (
id INT AUTO_INCREMENT
,version INT NOT NULL DEFAULT 1
,created_at TIMESTAMP NOT NULL DEFAULT NOW()
,updated_at TIMESTAMP NOT NULL
,name VARCHAR(64) NOT NULL
,index_id INT NOT NULL
,PRIMARY KEY(id)
,FOREIGN KEY(index_id) REFERENCES index_list(id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;
